version: '3.9'
services:
  landing-test:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "50305:3000"
    volumes:
      - type: bind
        source: /volume/files/services/recognid_landing-test
        target: /usr/src/app/logs


    environment:
      TZ: Europe/Kiev

    image: recognid-landing
    hostname: landing-test


    networks:
      mdfin:

#--test 2 3 4




networks:
  mdfin:









